export enum CategoriesEnum {
    // alligator = 'alligator',
    bear = 'bear',
    cat = 'cat',
    cow = 'cow',
    dog = 'dog',
    elephant = 'elephant',
    fish = 'fish',
    goat = 'goat',
    hedgehog = 'hedgehog',
    iguana = 'iguana',
    jellyfish = 'jellyfish',
    koala = 'koala',
    lion = 'lion',
    monkey = 'monkey',
    ostrich = 'ostrich',
    penguin = 'penguin',
    rinoceros = 'rinoceros',
    sheep = 'sheep',
    tiger = 'tiger',
    // turtle = '',
    // unicorn = '',
    // vulture = '',
    // wolf = '',
    // yak = '',
    // zebra = '',
}
